language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -q flask
    - pip install -q nose
    - pip install -q coverage
    - pip install -q web.py
    - pip install -q
    - pip install pep8
    - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 src"
    - pyflakes -x W src
script:
    - nosetests --with-coverage --with-xunit --cover-erase
    - coverage report
    
