language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -q flask --use-mirrors
    - pip install -q nose --use-mirrors
    - pip install -q coverage --use-mirrors
    - pip install -q web.py --use-mirrors
    - pip install -q  --use-mirrors
    - pip install pep8 --use-mirrors
    - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 src"
    - pyflakes -x W src
script:
    - nosetests --with-coverage --with-xunit --cover-erase
    - coverage report
