language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install -q flask
    - pip install -q nose
    - pip install -q coverage
    - pip install -q mock
    - pip install -q web.py
    - pip install -q pep8
before_script:
    - "rm -f .coverage coverage.xml"
    # http://pep8.readthedocs.org/en/latest/intro.html#error-codes
    # autopep8 --select="E1,E2,E3,W1,W2,W3" --in-place --aggressive --aggressive <filename>
    - "pep8 --exclude=migrations --ignore=E501,E265,E731 src"
script:
    - nosetests -s --with-coverage --with-xunit --cover-erase --xunit-file=coverage.xml
    - coverage report
